function test_tab
close('all');
hF = figure('MenuBar','none',...
    'Name','Test',...
    'NumberTitle','off',...
    'Position',[0 0 800 400]);
centerfig(hF);

p_input = uipanel(hF,'Units','Normalized',...
    'Title','Variables de entrada',...
    'Position',[0 0.02 0.25 0.96]);

p_output = uipanel(hF,'Units','Normalized',...
    'Title','Variables de salida',...
    'Position',[0.28 0.02 0.25 0.96]);

p_proc = uipanel(hF,'Units','Normalized',...
    'Title','Procedimiento',...
    'Position',[0.55 0.25 0.43 0.73]);

p_controls = uipanel(hF,'Units','Normalized',...
    'Position',[0.55 0.02 0.43 0.20]);


%% Datos de entrada
nombres_datos = load('VARS_BC.mat');
nombres_datos = nombres_datos.VARS_BC;
logic_val = false(size(nombres_datos));
hInputTab = uitable(p_input,'Data',logic_val,...
    'ColumnEditable',[true,false],...
    'Units','Normalized',...
    'RowName',nombres_datos,...
    'Position',[0 0 1 1]);

%% Datos de salida
hOutputTab = uitable(p_output,'Data',logic_val,...
    'ColumnEditable',[true,false],...
    'Units','Normalized',...
    'RowName',nombres_datos,...
    'Position',[0 0 1 1]);


%% Procedimiento
hTxtProc = uicontrol(p_proc,'style','edit',...
    'Units','Normalized',...
    'Position',[0.02 0.02 0.96 0.96],...
    'BackGroundColor','w',...
    'HorizontalAlignment','left',...
    'FontName','Courier New',...
    'FontSize',10,...
    'Max',1e5);

uicontrol(p_controls,'Style','Push',...
    'String','Generar plantilla',...
    'Units','Normalized',...
    'Position',[0.05 0.35 0.40 0.35],...
    'Callback',@genera_plantilla,...
    'FontSize',10,...
    'FontWeight','bold');

uicontrol(p_controls,'Style','Push',...
    'String','Ver ayuda',...
    'Units','Normalized',...
    'Position',[0.55 0.35 0.40 0.35],...
    'Callback','',...
    'FontSize',10,...
    'FontWeight','bold');


    function genera_plantilla(varargin)
        input_vars = get_vars(hInputTab);
        output_vars = get_vars(hOutputTab);
        proc = get(hTxtProc,'String');
        
        FILENAME = get_filename();
        fid = fopen(FILENAME,'w');
        % Write header
        THIS_INFO = {['function ',FILENAME(1:end-2)],...
            '% Código autogenerado por MFITEC v0.1.1',...
            ['% Fecha: ',datestr(now)],...
            '% BSD License'};
        for kk = 1:length(THIS_INFO)
            fprintf(fid,'%s\n',THIS_INFO{kk});
        end
        % Write Graphical User Interface
        createGUI(fid,input_vars);
        createProc(fid,input_vars,proc);
        fclose(fid);
        edit(FILENAME);
        %}
    end

    function createGUI(fid,ivars)
        NVARS = length(ivars);
        
    end

    function createProc(fid,ivars,proc)
        % Write input data
        for ii = 1:length(ivars)
            fprintf(fid,'%s\n',[ivars{ii},' = get(','d',ivars{ii},...
                ',','''String''',');']);
        end
        
        % Write proc
        for jj=1:size(proc,1)
            fprintf(fid,'%s\n',proc(jj,:));
        end
    end

    function r = get_filename()
        files = dir('user_def_*.m');
        if isempty(files)
            r = 'user_def_1.m'; % first
        else
            N = length(files)+1;
            r = ['user_def_',num2str(N),'.m'];
        end
    end

    function r = get_vars(hTab)
        data = get(hTab,'Data');
        rownames = get(hTab,'RowName');
        r = rownames(data);
    end

end